name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '20'
  REGISTRY_URL: 'https://registry.npmjs.org'

jobs:
  test:
    name: Test & Quality Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    env:
      NODE_OPTIONS: "--max_old_space_size=6144"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint || echo "Linting completed with warnings"

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Build verification
        run: npm run build:check

      - name: Upload build artifacts (Node 20 only)
        if: matrix.node-version == '20'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  docs:
    name: Documentation Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run docs:build

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-dist
          path: docs/.vitepress/dist/
          retention-days: 7

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level moderate || echo "Security audit completed with warnings"

  quality-gate:
    name: Quality Gate Summary
    runs-on: ubuntu-latest
    needs: [test, docs, security]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Quality gate summary
        run: |
          echo "✅ All quality checks passed!"
          echo "🧪 Tests: Passed across Node.js 18 & 20"
          echo "📚 Documentation: Built successfully"
          echo "🔒 Security: Audit completed"
          echo ""
          echo "📦 Project ready for automated release pipeline"
          echo "ℹ️  Release will be triggered automatically if version changed"

