name: Pull Request Validation & Merge

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

jobs:
  pr-validation:
    name: PR Quality Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    outputs:
      validation-passed: ${{ steps.validation.outputs.passed }}
    
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run PR validation
        id: validation
        run: |
          echo "Running comprehensive PR validation..."
          
          # Check for breaking changes
          if git diff --name-only origin/main...HEAD | grep -E "(package\.json|tsconfig\.json|src/.*\.ts)" > /dev/null; then
            echo "Code changes detected - running full validation"
            
            # Build and test
            npm run build
            npm run test:unit
            npm run build:check
            
            # Documentation check
            npm run docs:build
            
            echo "passed=true" >> $GITHUB_OUTPUT
          else
            echo "No critical files changed - validation passed"
            echo "passed=true" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const validationPassed = '${{ steps.validation.outputs.passed }}' === 'true';
            
            const body = validationPassed 
              ? `✅ **PR Validation Passed**
                
                All quality checks have passed:
                - ✅ Build successful
                - ✅ Tests passing
                - ✅ Documentation builds correctly
                
                This PR is ready for review and merge.`
              : `❌ **PR Validation Failed**
                
                Some quality checks failed. Please review the workflow logs and fix the issues.`;
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body
            });

  auto-merge:
    name: Auto-merge PR
    runs-on: ubuntu-latest
    needs: pr-validation
    if: |
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved' &&
      needs.pr-validation.outputs.validation-passed == 'true'
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge PR
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          echo "Merging PR #$PR_NUMBER: $PR_TITLE"
          
          # Fetch the PR branch
          git fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER
          
          # Merge the PR
          git merge --no-ff pr-$PR_NUMBER -m "Merge pull request #$PR_NUMBER: $PR_TITLE

          🤖 Auto-merged by GitHub Actions after approval
          
          Co-Authored-By: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.login }}@users.noreply.github.com>"
          
          # Push to main
          git push origin main

      - name: Close PR
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            
            await github.rest.pulls.update({
              owner,
              repo,
              pull_number: prNumber,
              state: 'closed'
            });
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: `🎉 **Auto-merged to main**
              
              This pull request has been automatically merged after approval.
              
              - ✅ All quality checks passed
              - ✅ Approved by reviewer
              - ✅ Merged successfully
              
              🤖 Automated by GitHub Actions`
            });

  merge-notification:
    name: Merge Notification
    runs-on: ubuntu-latest
    needs: auto-merge
    if: success()
    
    steps:
      - name: Success notification
        run: |
          echo "🎉 Pull request successfully auto-merged to main!"
          echo "📦 Next: If version was bumped, package will be published automatically"
          echo "📖 Documentation will be updated on GitHub Pages"